name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
prerelease: false
exclude-labels:
  - "skip-changelog"
categories:
  - title: "🚀 Features"
    labels:
      - "new-feature"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📖 Docs"
    labels:
      - "docs"
  - title: "📦 Dependencies"
    labels:
      - "dependencies"
  - title: "🧰 Maintenance"
    label: "chore"

version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
  patch:
    labels:
      - "type: bug"
      - "type: maintenance"
      - "type: docs"
      - "type: dependencies"
      - "type: security"

change-template: "- #$NUMBER: $TITLE"
template: |
  ## Changes

  $CHANGES
